name: Terraform Lint and Security Scan

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab in GitHub


jobs:
  lint-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install tflint for Terraform linting
      - name: Install tflint
        run: curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r .assets[0].browser_download_url)" -o /usr/local/bin/tflint && chmod +x /usr/local/bin/tflint

      # Install tfsec for security scanning
      - name: Install tfsec
        run: curl -L "$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | jq -r .assets[0].browser_download_url)" -o /usr/local/bin/tfsec && chmod +x /usr/local/bin/tfsec

      # Run tflint
      - name: Run tflint
        run: tflint

      # Run tfsec
      - name: Run tfsec
        run: tfsec .
